# general
#IMG_WIDTH=320
#IMG_HEIGHT=75
batch_size: 20
input_size_w: 320
input_size_h: 75
embd_shape: 512
sub_name: 'MobileNetV2_2ed'
1st_sub_name: 'MobileNetV2'
backbone_type: 'MobileNetV2' # 'ResNet50', 'MobileNetV2' VGG16
head_type: NormHead # 'ArcHead', 'NormHead'
is_ccrop: True # central-cropping or not
rnn: False
# train
# url https://www.dropbox.com/s/9w1hb95t5ty8te7/tent_300_bin.tfrecord?dl=0
train_dataset: './data/tent_300_bin.tfrecord'
binary_img: True
num_classes: 10
#1848
num_samples: 400
epochs: 80
base_lr: 0.001
w_decay: !!float 5e-4
save_steps: 100

# test
test_dataset: './data/test_dataset'
