# general
batch_size: 20
input_size_w: 44
input_size_h: 44
embd_shape: 512
sub_name: 'ResNet50_2ed'
1st_sub_name: 'ResNet50_1028'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2' VGG16
head_type: NormHead # 'NormHead'
is_ccrop: True # central-cropping or not
rnn: False
# train
num_classes: 319
#1848
num_samples: 10000
epochs: 100
base_lr: 0.0001
w_decay: !!float 5e-4
save_steps: 10000
