# general
#IMG_WIDTH=320
#IMG_HEIGHT=75
batch_size: 20
input_size_w: 320
input_size_h: 75
embd_shape: 512
sub_name: 'arc_ResNet50'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2' VGG16
head_type: NormHead # 'ArcHead', 'NormHead'
is_ccrop: True # central-cropping or not

# train
# url https://www.dropbox.com/s/9w1hb95t5ty8te7/tent_300_bin.tfrecord?dl=0
train_dataset: './data/New_ROI_STLT_bin.tfrecord'
binary_img: True
num_classes: 319
#1848
num_samples: 17233
epochs: 100
base_lr: 0.01
w_decay: !!float 5e-4
save_steps: 10000

# test
test_dataset: './data/test_dataset'
