# general
#IMG_WIDTH=320
#IMG_HEIGHT=75
batch_size: 20
input_size_w: 128
input_size_h: 128
embd_shape: 512
sub_name: 'VGG16_1028'
backbone_type: 'VGG16' # 'ResNet50', 'MobileNetV2' VGG16
head_type: NormHead # 'NormHead'
is_ccrop: True # central-cropping or not
rnn: False
# train
num_classes: 319
#1848
num_samples: 10000
epochs: 50
base_lr: 0.01
w_decay: !!float 5e-4
save_steps: 10000
